In [7]:
#1.WAP(Write a program) to Create an Empty and a Full NumPy Array?
import numpy as np
empty_array=np.empty((2,3))
full_array=np.full((3,3),5)
print("Empty array:\n",empty_array)
print("Full array:\n",full_array)

Empty array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Full array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [14]:
#2.WAP to Remove rows in Numpy array that contains non-numeric values?
import numpy as np
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])
print("Original array:")
print(x)
print("Remove all non-numeric elements of the said array")
print(x[~np.isnan(x).any(axis=1)])

Original array:
[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
Remove all non-numeric elements of the said array
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


In [22]:
#3.WAP to Find the number of occurrences of a sequence in a NumPy array?
import numpy
arr = numpy.array([[13,7,6,8],
                   [9,13,7,8],
                   [4,6,13,8],
                   [13,7,6,9]])
output = repr(arr).count("6")
print(output)

3


In [24]:
#4.WAP to Find the most frequent value in a NumPy array?
import numpy as np
arr = np.array([13,5,7,13,6,8,13,9,13,])
print("Original array:")
print(arr)  
print("Most frequent value in the above array:")
print(np.bincount(arr).argmax())

Original array:
[13  5  7 13  6  8 13  9 13]
Most frequent value in the above array:
13


In [27]:
#5.WAP to build an array of add of two NumPy arrays?
import numpy as np
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])
print("Array-1:\n",array_1) 
print("Array-2:\n",array_2)  
add = array_1+array_2 
print("Combine array:\n",add)

Array-1:
 [1 2]
Array-2:
 [4 6]
Combine array:
 [5 8]


In [28]:
#6.WAP to Return the indices of elements where the given condition is satisfied.
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])  
print(a)  
print ('Indices of elements <4')  
b = np.where(a<4)
print(b)  
print("Elements which are <4")
print(a[b])

[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
Elements which are <4
[1 2 3]


In [29]:
#7.WAP to Multiplying a matrix (numpy array) by a scalar
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print ("Original matrix = ")
print (matrix)
scalar = 2
new_matrix = matrix * scalar
print ("Matrix x Scalar = ")
print (new_matrix)

Original matrix = 
[[1 2 3]
 [4 5 6]]
Matrix x Scalar = 
[[ 2  4  6]
 [ 8 10 12]]


In [32]:
#8.WAP to Array re-dimensioning of giving data.
import numpy as np
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])
reshaped_array=a.reshape(3,2)
print("Original aray:\n",a)
print("Reshaped array:\n",reshaped_array)

Original aray:
 [[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]
Reshaped array:
 [[2.5  3.8 ]
 [1.5  4.7 ]
 [2.9  1.56]]


In [34]:
#9.WAP to Obtaining Boolean Array from Binary Array of given data?
import numpy as np
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])
boolean=a==1
print("Binary array:\n",a)
print("Boolean array:\n",boolean)

Binary array:
 [[1 0 0]
 [1 1 1]
 [0 0 0]]
Boolean array:
 [[ True False False]
 [ True  True  True]
 [False False False]]


In [37]:
#10.WAP to Horizontal Stacking of Numpy Arrays?
import numpy as np
arr1 = np.array([[ 1, 2, 3],[3,5,6]])
print ("1st Input array : \n", arr1)   
arr2 = np.array([[4, 5, 6],[2,5,8]])
print ("2nd Input array : \n", arr2)   
arr3 = np.hstack((arr1, arr2))
print ("Output horizontally stacked array:\n ", arr3)

1st Input array : 
 [[1 2 3]
 [3 5 6]]
2nd Input array : 
 [[4 5 6]
 [2 5 8]]
Output horizontally stacked array:
  [[1 2 3 4 5 6]
 [3 5 6 2 5 8]]


In [41]:
#11.Array Generation of random integers within a specified range?
import random 
print("Random integers between 0 and 9: ")
for i in range(1,10):
    y = random.randrange(9)
    print(y)

Random integers between 0 and 9: 
0
1
7
1
8
3
0
0
4


In [42]:
#12.Matrix Multiplication of Given Data?
import numpy as np
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
result=np.multiply(a,b)
print("Matrix a:\n",a)
print("Matrix b:\n",b)
print("Multiplication of a and b matrix:\n",result)

Matrix a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix b:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Multiplication of a and b matrix:
 [[ 2  6 12]
 [20 30 42]
 [56 72 90]]
